In [1]:
import trimesh
import numpy as np
from pathlib import Path

In [2]:
PROJECT_ROOT = Path(".").resolve().parent
#PROJECT_ROOT = Path("/home/salman/rai_workspace/Voxel_manipulation_v2/pose_estimation")

MESH_INPUT  = PROJECT_ROOT / "environments/mesh_dataset/lamp/lamp_0001.ply"
MESH_OUTPUT = PROJECT_ROOT / "megapose_objects/lamp/mesh.ply"

MESH_SCALE = 0.000271579  # meshscale from the .g scene file

MESH_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

In [3]:
mesh = trimesh.load(str(MESH_INPUT))
print(f"Loaded:  {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")
print(f"Bounds before scaling:\n  {mesh.bounds}")
print(f"Extents before scaling: {mesh.extents}")

Loaded:  7790 vertices, 15328 faces
Bounds before scaling:
  [[-128.87600708 -128.87600708 -214.71800232]
 [ 128.87600708  128.87600708  126.28199768]]
Extents before scaling: [257.75201416 257.75201416 341.        ]


In [4]:
mesh.apply_scale(MESH_SCALE)

print(f"Bounds after scaling (meters):\n  {mesh.bounds}")
print(f"Extents after scaling (meters): {mesh.extents}")
print(f"Longest dimension: {mesh.extents.max():.4f} m")

Bounds after scaling (meters):
  [[-0.03500002 -0.03500002 -0.0583129 ]
 [ 0.03500002  0.03500002  0.03429554]]
Extents after scaling (meters): [0.07000003 0.07000003 0.09260844]
Longest dimension: 0.0926 m


In [5]:
mesh.export(str(MESH_OUTPUT))
print(f"Saved scaled mesh -> {MESH_OUTPUT}")

Saved scaled mesh -> /home/salman/rai_workspace/Voxel_manipulation_v2/pose_estimation/megapose_objects/lamp/mesh.ply
